#apps name
name: chorus_app
#apps description
description: Chorus, a Choir Hub app

#apps version
version: 0.0.1

#apps author
author: Ryan Morrison <ryanmorrison@gmail.com>

#apps sdk environment
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

#apps production dependencies
dependencies:
  flutter:
    sdk: flutter
  audio_recorder2: ^1.0.3
  cupertino_icons: ^0.1.2
  file: ^5.0.4
  flutter_sound: ^1.0.6
  http: ^0.12.0+1
  intl: ^0.15.7
  localstorage: ^1.0.0
  path_provider: ^0.4.1
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.0
  simple_permissions: ^0.1.9
  uuid: 1.0.3

#apps development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

#dart dependencies

flutter:

  uses-material-design: true

  assets:
  - res/icons/ic_play.png
  - res/icons/ic_stop.png
  - res/icons/ic_pause.png
  - res/icons/ic_mic.png
  - res/icons/ic_volume_down.png
  - res/icons/ic_volume_up.png
  - assets/dog.jpg
  - assets/background.jpg



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/Oswald-Bold.ttf
          weight: 700
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
